### ISSUE TITLE
Uncaught Error: Connection is disposed.

### ISSUE THREAD

**Issue by laughedelic** [laughedelic/atom-ide-scala#72]
[Enter steps to reproduce:]

Just switching between `.scala` files. 

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Mac OS X 10.14.1
**Thrown From**: [ide-scala](https://github.com/laughedelic/atom-ide-scala) package 0.8.1

### Stack Trace

Uncaught Error: Connection is disposed.

```
At /Users/alexey.alekhin/.atom/packages/ide-scala/node_modules/vscode-jsonrpc/lib/main.js:664

Error: Connection is disposed.
    at throwIfClosedOrDisposed (/packages/ide-scala/node_modules/vscode-jsonrpc/lib/main.js:664:19)
    at Object.sendNotification (/packages/ide-scala/node_modules/vscode-jsonrpc/lib/main.js:711:13)
    at LanguageClientConnection._sendNotification (/packages/ide-scala/node_modules/atom-languageclient/build/lib/languageclient.js:364:19)
    at LanguageClientConnection.sendCustomNotification (/packages/ide-scala/node_modules/atom-languageclient/build/lib/languageclient.js:91:14)
    at /packages/ide-scala/lib/main.js:5958:15)
    at /packages/ide-scala/lib/main.js:5881:50
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190583)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1192024)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:424391)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:38690)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190583)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1192024)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:446453)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:455309)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:457479)
    at TabBarView.t.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1141088)
```

### Commands

```
     -6:41.9.0 core:save (input.hidden-input)
  2x -6:22.9.0 window:toggle-dev-tools (a.stack-toggle)
     -2:52.6.0 datatip:toggle (input.hidden-input)
  3x -2:45.4.0 find-and-replace:select-next (input.hidden-input)
     -2:44 find-and-replace:select-all (input.hidden-input)
     -2:43.1.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -2:42.6.0 editor:toggle-line-comments (input.hidden-input)
     -2:42.2.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -2:41.8.0 core:save (input.hidden-input)
 11x -2:34.4.0 find-and-replace:select-next (input.hidden-input)
     -2:31.4.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -2:30.4.0 editor:toggle-line-comments (input.hidden-input)
     -2:30 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -2:29.6.0 core:save (input.hidden-input)
     -1:54.1.0 settings-view:open (input.hidden-input)
     -1:00.5.0 core:copy (div.package-readme.native-key-bindings)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-ide-ui 0.13.0 
autocomplete-paths 2.12.2 
base16-syntax 1.8.1 
bracket-colorizer 1.2.0 
cursor-history 0.13.1 
file-icons 2.1.26 
highlight-selected 0.14.0 
hyperlink-hyperclick 2.0.0 
ide-json 0.2.1 
ide-scala 0.8.1 
key-peek 0.2.12 
language-gitignore 0.3.0 
language-jenkinsfile 0.1.1 
language-scala 1.1.9 
language-sql-bigquery 0.2.8 
markdown-preview-enhanced 0.15.8 
project-folder 1.5.0 
simple-align 0.2.0 
vim-mode-plus 1.36.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by AlexDaciuk** [comment]
[Enter steps to reproduce:]

1. Open any scala file
2. Wait for the Error to happen

Sometimes it can take a few minutes, sometimes seconds

**Atom**: 1.38.1 x64
**Electron**: 4.1.4
**OS**: linux 5.1.9-arch1-1-ARCH
**Thrown From**: [ide-scala](https://github.com/laughedelic/atom-ide-scala) package 0.10.0


### Stack Trace

Uncaught Error: Connection is disposed.

```
At /home/alexarch/.atom/packages/ide-scala/node_modules/vscode-jsonrpc/lib/main.js:664

Error: Connection is disposed.
    at throwIfClosedOrDisposed (/packages/ide-scala/node_modules/vscode-jsonrpc/lib/main.js:664:19)
    at Object.sendNotification (/packages/ide-scala/node_modules/vscode-jsonrpc/lib/main.js:711:13)
    at LanguageClientConnection._sendNotification (/packages/ide-scala/node_modules/atom-languageclient/build/lib/languageclient.js:364:19)
    at LanguageClientConnection.sendCustomNotification (/packages/ide-scala/node_modules/atom-languageclient/build/lib/languageclient.js:91:14)
    at /packages/ide-scala/lib/main.js:96:77
    at CallbacksRegistry.apply (/usr/lib/electron/resources/electron.asar/renderer/callbacks-registry.js:47:25)
    at handleMessage (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:285:21)
    at EventEmitter.ipcRenderer.on.args (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:275:7)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -5:42 core:confirm (input.hidden-input)
  2x -3:21.5.0 core:close (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
autocomplete 0.47.0 
autocomplete-python 1.14.0 
autoupdate-packages 1.3.1 
browser-plus 0.0.98 
busy-signal 2.0.1 
dash-syntax 0.4.2 
dockerletion 0.2.0 
emmet 2.4.3 
file-icons 2.1.33 
highlight-line 0.12.0 
highlight-selected 0.16.0 
hyperclick 0.0.0 
ide-python 1.4.1 
ide-scala 0.10.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-docker 1.1.8 
language-scala 1.1.10 
linter 2.3.0 
linter-docker 0.3.2 
linter-eslint 8.5.5 
linter-flake8 2.4.0 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
python-tools 0.6.9 
react-es6-snippets 0.3.0 
sbt 0.13.0 
scala-code-formatter 0.2.0 
script 3.18.1 
sync-settings 0.8.6 
```

**Comment by laughedelic** [comment]
@AlexDaciuk please try v0.10.1, it should fix this.
