### ISSUE TITLE
Failed to activate the ide-scala package

### ISSUE THREAD

**Issue by xiligey** [laughedelic/atom-ide-scala#80]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 专业版
**Thrown From**: [ide-scala](https://github.com/laughedelic/atom-ide-scala) package 0.9.0

### Stack Trace

Failed to activate the ide-scala package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at StatusBarView.t.exports.StatusBarView.addRightTile (<embedded>:11:962543)
    at a.consumeStatusBar (/packages/ide-scala/lib/main.js:221:399)
    at Object.m.consumeStatusBar (/packages/ide-scala/lib/main.js:454:225)
    at Provider.t.exports.Provider.provide (<embedded>:14:1040915)
    at ServiceHub.t.exports.ServiceHub.consume (<embedded>:11:3534107)
    at Package.activateServices (<embedded>:11:3542239)
    at Package.activateNow (<embedded>:11:3539073)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (<embedded>:14:2445)
    at Function.simpleDispatch (<embedded>:11:1174290)
    at Emitter.emit (<embedded>:11:1175731)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (<embedded>:11:382852)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (<embedded>:11:382814)
    at <embedded>:11:901281
    at r (<embedded>:11:895887)
    at n (<embedded>:14:1043822)
    at ChildProcess.o.process.on.e (<embedded>:14:1044028)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-bash-builtins 0.3.5 
autocomplete-python 1.14.0 
busy-signal 2.0.1 
file-icons 2.1.33 
fonts 3.4.0 
Hydrogen 2.9.0 
hyperclick 0.1.5 
ide-scala 0.9.0 
indent-detective 0.3.2 
ink 0.10.10 
intentions 1.1.5 
julia-client undefined 
kite 0.164.0 
language-julia 0.19.0 
language-scala 1.1.10 
latex-completions 0.3.6 
linter 2.3.0 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
markdown-preview-enhanced 0.16.0 
open-file 1.4.0 
platformio-ide-terminal 2.9.1 
project-manager 3.3.7 
python-autopep8 0.1.3 
python-isort 0.0.7 
quick-query 1.1.0 
remote-ftp 2.2.2 
script 3.18.1 
todo-show 2.3.2 
tool-bar 1.1.11 
tortoise-svn 0.5.1 
uber-juno 0.2.0 
```

**Comment by laughedelic** [comment]
Hi @xiligey! From the plugins list it seems that you don't have atom-ide-ui installed. Try to install it manually.

The ide-scala package is supposed to install this dependency if it's needed, so it's surprising anyway. Have installed it for the first time or upgraded from an older version?

**Comment by laughedelic** [comment]
I'll close this for now. Please update the package, install atom-ide-ui and let me know if this is still a problem.
